### PR TITLE
OpenMP Target Resource Fixes

### LINKED ISSUE #1092: OpenMP Target Build Issue
When building with OpenMP and Offloading enabled, test-kernel-basic-single-loop-Segments-OpenMPTarget.exe (and others) are hitting errors bc of a missing forall_impl implementation.

I've run into the issue with XL 16.01 and Clang 11.0.1, both on Lassen.

**Steps to Reproduce**
```
mkdir build
cd build
cmake -DENABLE_OPENMP=On -DENABLE_TARGET_OPENMP=On ..
make test-kernel-basic-single-loop-Segments-OpenMPTarget.exe
```

It looks like the problem is that the kernel call is using a Host resource, while the available omp_target forall_impls all expect a Omp resource.

**Fix**

adding the following to include/RAJA/policy/openmp_target/forall.hpp fixes the issue for me. All I did was copy the existing implementation and change the return and first argument's type (and name) from resources::Omp to resources::Host.

```
template <typename Iterable, typename Func>
RAJA_INLINE resources::EventProxy<resources::Host> forall_impl(resources::Host host_res,
                                                              const omp_target_parallel_for_exec_nt&,
                                                              Iterable&& iter,
                                                              Func&& loop_body)
{
  using Body = typename std::remove_reference<decltype(loop_body)>::type;
  Body body = loop_body;

  RAJA_EXTRACT_BED_IT(iter);

#pragma omp target teams distribute parallel for schedule(static, 1) \
    firstprivate(body,begin_it)
  for (decltype(distance_it) i = 0; i < distance_it; ++i) {
    Body ib = body;
    ib(begin_it[i]);
  }

  return resources::EventProxy<resources::Host>(host_res);
}
```

### PR DESCRIPTION
**Pull request by brandonneth**
# Summary

- This PR is a bug fix 
- It does the following:
  - Fixes #1092 and #1093 
  - Fixes resource selection process for nested kernels.

The existence of these bugs also suggests there should be more CI/CD testing of OpenMP target offloading, as without these changes, OpenMP target offloading tests do not build at all. 
 
Thank you @trws for the help figuring out what was causing the issues!

### CODE REVIEW

**Comment by rhornung67** [comment]
Thanks for the fixes @brandonneth I added some reviewers to your PR.

Part of the problem here may have been the result of spotty compiler support whereby code would work for one compiler version and not another (both XL and clang). Plus, we don't spend much time on the OpenMP target stuff because no one uses it in any serious way. It's not very well tested because our tests for this back-end take a very long time to build.

**Comment by brandonneth** [comment]
@rhornung67 The build time is killer! That was the longest part of figuring out this issue.

File: include/RAJA/pattern/kernel/For.hpp [hunk 1]
```diff
@@ -101,7 +101,8 @@ struct StatementExecutor<
     auto len = segment_length<ArgumentId>(data);
     using len_t = decltype(len);
 
-    auto r = data.res;
```
Comment (trws) [inline include/RAJA/pattern/kernel/For.hpp:104]: Does this change remain necessary? The resource passed in here should be the right one when the user is passing one in, and we probably don't want to disable that.  Will the rest work if this change is pulled out?

**Review by trws — CHANGES_REQUESTED** [review]
Aside from the one spot in For, this looks great.  Thanks again for finding and tracking this down @brandonneth!

File: include/RAJA/pattern/kernel/For.hpp (hunk 1 above)
Comment (brandonneth) [reply include/RAJA/pattern/kernel/For.hpp:104]: Changing it back breaks the following example:
```
Policy = KernelPolicy<
  For<0,seq,
    For<1,omp_target
      Lambda<0>>>>;

kernel<Policy>(...) // no resource specified
```

**The issue:**

kernel<Policy> creates a default resource based on Policy. 
Default resource creates the default based on get_platform<Policy>. 
This should basically resolve to platform_max(omp_target, host) = omp_target.
Default resource for omp_target is resource::Omp
So we have resource::Omp being passed to the LoopData constructor and then used throughout the execution.

When we get to the first StatementExecutor, which is for seq_exec, we're gonna call forall_impl for a seq_exec and resource::Omp. No such forall_impl exists.

**Alternative change:** 
Implement a forall_impl for a seq_exec policy and a omp resource. 

Do you anticipate implementing such a forall_impl to cause any other issues?

**Comment by trws** [comment]
Ouch, I hadn’t thought about that, but it begs an interesting 
question.  Does that case work for a cuda inner policy? If it doesn’t 
then I’d say leave it broken but maybe file an issue about it.

If on the other hand it does work, then we’ll need to solve this.  If 
we do need to solve it I think the right thing to do is going to be 
somewhat complicated, and involve being able to take multiple resources 
so we can get ones of the right types for all the policies inside a 
kernel policy, which could get kinda rough.

**Comment by brandonneth** [comment]
So the example above comes from test-kernel-nested-loop-Basic-OpenMPTarget.exe. Fixing it requires a forall_impl to be included for both loop_exec and seq_exec. I've added those (wrapped in a check for openmp) and they seem to work just fine. 

For CUDA, the current tests don't use this configuration, but if I add an example that does 
```
For<cuda_exec<64>,
  For<seq_exec
...
```
or
```
For<seq_exec
  For<cuda_exec<64>,
...
```

the code no longer compiles. The current tests use cuda_thread_{x,y}_loop, which do not include policy, pattern, launch, or platform information. 

I'm not sure what you mean by "if this case works", but I'm guessing that CUDA code not compiling is something we want to fix.

**Comment by trws** [comment]
I'm ok with fixing it if we can do it consistently, but if it isn't supported for cuda that means nobody is using the ability to do this in production, and it might be better to defer trying to support this kind of multi-kernel case until we need it.  @rhornung67, @MrBurmark, @ajkunen have any of you run into a case where someone wants to be able to use kernel to run a sequential loop on the host over a number of kernel launches such that it would be valuable to allow that corner case?

**Comment by brandonneth** [comment]
for fixing it consistently, I think forall_impl's for the product of (loop_exec,seq_exec) x (omp,cuda,hip) should cover it

**Comment by MrBurmark** [comment]
@trws I don't have a use case for this.

**Comment by trws** [comment]
It would cover all the serial cases, but do we then support the host threading cases?  I'm not sure.  My first thought would be we have a way to tag all the host policies such that we can make a forall_impl that will accept any of the host policies on the outside, and device policies on the inside if we go that way.

**Comment by brandonneth** [comment]
Thats a good point, I think I’m leaning towards changing the policies we use in the test cases and adding some sort of spec requirement that policies and resources need to be compatible throughout the entire kernel policy.

**Comment by rchen20** [comment]
Just ran in to this compilation issue while trying the newest compilers on OpenMP Target; thanks @brandonneth for looking in to this!

> I'm ok with fixing it if we can do it consistently, but if it isn't supported for cuda that means nobody is using the ability to do this in production, and it might be better to defer trying to support this kind of multi-kernel case until we need it. @rhornung67, @MrBurmark, @ajkunen have any of you run into a case where someone wants to be able to use kernel to run a sequential loop on the host over a number of kernel launches such that it would be valuable to allow that corner case?

@trws @rhornung67 I don't think we need this use case at the moment, although the code I work on has the following host threading with CUDA kernels implementation for using concurrent streams:

`#pragma omp parallel do`
`  cudastreamkernel<<<. . .>>>(. . .)`
`#pragma omp end parallel do`

Maybe we can implement this functionality another time, but for now if someone needs this, they can manually create omp host threads over RAJA CUDA kernels.

**Comment by brandonneth** [comment]
The change I ended up going with was to template the resource type for the sequential forall_impl functions so you can have a nested loop that has different policy types (omptarget then seq or  cuda then seq), but doesn't allow mixing of policy types beyond that. If we don't want to have the sequential forall_impl support other resource types, then we should probably just remove the tests, because it's testing a feature we don't support.

**Comment by trws** [comment]
That sounds quite reasonable to me.  Am I reading this right that it will take a resource for the portion that uses offload and just pass it through the outer sequential layers?

**Comment by brandonneth** [comment]
@trws Yes. The default resource for a KernelPolicy is calculated like:
```
highestPriorityPlatform = max( [ExecPol.platform for ExecPol in KernelPolicy] )
return highestPriorityPlatform.defaultResource
```
Sequential is the lowest priority, mapping to resource::Host, while target_openmp is higher priority, mapping to resource::Omp. This highest priority resource is then passed through the entire loop nest as part of the LoopData data structure.  

cuda is a higher priority than omptarget, so the policy
For<..., seq,
  For<... omptarget,
     For<..., cuda,...>>>
would create a resources::Cuda, which would work fine for the outer For (due to the templating I added), but would break for the omptarget For, as those implementations require a resources::Omp.

**Review by trws — APPROVED** [review]
