### PR TITLE
Fix exclusive scan with const-iterators

### LINKED ISSUE #1191: Scan exclusive compile error
Current raja release. I am using llvm clang 13.0.0 with serial, openmp and cuda configured. This only happens with the `RAJA::seq_exec`.
Anyone seen this before:

```
raja/include/RAJA/policy/sequential/scan.hpp(157): error: expression must be a modifiable lvalue
          detected during:
            instantiation of "camp::concepts::enable_if_t<camp::resources::v1::EventProxy<camp::resources::v1::Host>, RAJA::type_traits::is_sequential_policy<ExecPolicy>> RAJA::impl::scan::exclusive(camp::resources::v1::Host, const ExecPolicy &, Iter, Iter, OutIter, BinFn, T) [with ExecPolicy=luminary::vis::SerialExec::for_policy, Iter=const luminary::vis::Id *, OutIter=luminary::vis::Id *, BinFn=RAJA::operators::plus<luminary::vis::Id, luminary::vis::Id, luminary::vis::Id>, T=luminary::vis::Id]" 
/home/mclarsen/.cache/bazel/_bazel_mclarsen/bdd0657b05cd1ca06a9a049087540106/external/raja/include/RAJA/pattern/scan.hpp(292): here
            instantiation of "camp::concepts::enable_if_t<camp::resources::v1::EventProxy<Res>, RAJA::type_traits::is_execution_policy<ExecPolicy>, RAJA::type_traits::is_resource<Res>, std::is_constructible<camp::resources::v1::Resource, Res>, camp::type_traits::is_range<InContainer>, camp::type_traits::is_range<OutContainer>> RAJA::policy_by_value_interface::exclusive_scan(ExecPolicy &&, Res, InContainer &&, OutContainer &&, Function, T) [with ExecPolicy=luminary::vis::SerialExec::for_policy, Res=camp::resources::v1::Host, InContainer=RAJA::Span<const luminary::vis::Id *, luminary::vis::Id>, OutContainer=RAJA::Span<luminary::vis::Id *, luminary::vis::Id>, T=luminary::vis::Id, Function=RAJA::operators::plus<luminary::vis::Id, luminary::vis::Id, luminary::vis::Id>]"
```

I have the distinct feeling that I have seen this before, but I couldn't find any issues relating to this.

### PR DESCRIPTION
**Pull request by MrBurmark**
# Summary
Fix exclusive scan with const-iterators

Also make loop and sequential implementations consistent.

- This PR is a bugfix and refactoring
- It does the following (modify list as needed):
  - refactors loop scan implementation to match sequential where appropriate
  - Fixes #1191

### CODE REVIEW

File: include/RAJA/policy/loop/scan.hpp [hunk 1]
```diff
@@ -51,10 +51,11 @@ inclusive_inplace(
     Iter end,
     BinFn f)
 {
-  auto agg = *begin;
+  using ValueT = typename std::remove_reference<decltype(*begin)>::type;
+  ValueT agg = *begin;
 
   for (Iter i = ++begin; i != end; ++i) {
-    agg = f(*i, agg);
+    agg = f(agg, *i);
```
Comment (rhornung67) [inline include/RAJA/policy/loop/scan.hpp:58]: what's going on with the transposed function args here and below?

File: test/functional/scan/tests/test-scan-Exclusive.hpp [hunk 2]
```diff
@@ -54,7 +54,7 @@ void ScanExclusiveTestImpl(int N,
   res.memcpy(work_in, host_in, sizeof(T) * N);
   res.wait();
 
-  RAJA::exclusive_scan<EXEC_POLICY>(RAJA::make_span(work_in, N),
+  RAJA::exclusive_scan<EXEC_POLICY>(RAJA::make_span(static_cast<const T*>(work_in), N),
```
Comment (rhornung67) [inline test/functional/scan/tests/test-scan-Exclusive.hpp:57]: are we still testing the non-const case? or, do we need to?

Comment (MrBurmark) [reply test/functional/scan/tests/test-scan-Exclusive.hpp:57]: We should not need to as this case is more restrictive, but it would be easy to just cast one of the two scans.

File: include/RAJA/policy/loop/scan.hpp (hunk 1 above)
Comment (MrBurmark) [reply include/RAJA/policy/loop/scan.hpp:58]: I don't know why this discrepancy existed, but the new order seems more right to me, though though it shouldn't matter as our operator should be commutative.

Comment (rhornung67) [reply include/RAJA/policy/loop/scan.hpp:58]: At any rate, good catch! 👍

**Review by rhornung67 — APPROVED** [review]
Thanks @MrBurmark !

**Review by artv3 — APPROVED** [review]

File: include/RAJA/policy/loop/scan.hpp (hunk 1 above)
Comment (willkill07) [reply include/RAJA/policy/loop/scan.hpp:58]: I looked at the blame history and it was my fault :\ dunno what I was doing there.

**Comment by rhornung67** [comment]
@MrBurmark should we merge this? I don't think this change would break the Hip back-end.

**Comment by MrBurmark** [comment]
Sure, I'll force this through.
