### PR TITLE
Fix kernel to not launch a kernel if there is no work

### LINKED ISSUE #1733: Kernel may launch GPU kernel with no work
**Describe the bug**

Sometimes kernel will launch gpu kernels even though they have no work to do.
The gpu implementation of kernel tracks the number of blocks/threads requested and a minimum number of blocks/threads required in each dimension to choose appropriate numbers of blocks and threads. It uses 0 as the default number of blocks/threads and then only chooses not to launch a kernel if all dimensions are still 0 after calculating dimensions.

**To Reproduce**

Use kernel with a 2d loop over ranges of size 1 and 0 respectively.

**Expected behavior**

Kernel should not launch a kernel if any dimension in a gpu policy has no work.

**Compilers & Libraries (please complete the following information):**
 - CUDA/HIP version: any

**Additional context**

Discovered this when I saw segfaults while trying out new "unchecked" policies with 0 length list segments in the test-kernel-nested-loop-segments-HIP test.

### PR DESCRIPTION
**Pull request by MrBurmark**
# Fix kernel to not launch a kernel if there is no work

Track which dimensions are active when calculating dimensions in kernel. This allows us to know that we have no work to do in some cases where there was ambiguity before and kernels were launched despite having no work.

- This PR is a bugfix
- It does the following (modify list as needed):
  - Fixes #1733

### CODE REVIEW

File: include/RAJA/policy/cuda/kernel/internal.hpp [hunk 1]
```diff
@@ -259,16 +286,23 @@ struct KernelDimensionCalculator<RAJA::policy::cuda::cuda_indexer<
...
           "len exceeds the size of the directly mapped index space");
     }
-    set_cuda_dim<dim>(dims.threads, static_cast<IdxT>(IndexMapper::block_size));
-    set_cuda_dim<dim>(min_dims.threads,
-                      static_cast<IdxT>(IndexMapper::block_size));
+
+    LaunchDims dims;
+
+    set_cuda_dim<dim>(dims.  active.threads, static_cast<cuda_dim_member_t>(true));
+    set_cuda_dim<dim>(dims.    dims.threads, static_cast<cuda_dim_member_t>((len > zero) ? IndexMapper::block_size : 0));
```
Comment (adayton1) [inline include/RAJA/policy/cuda/kernel/internal.hpp:302]: Can you use "zero" instead of "0"?

Comment (adayton1) [reply include/RAJA/policy/cuda/kernel/internal.hpp:322]: Oh, I didn't realize it was an int in these cases. I don't think it really adds any clarity to make changes, so it's probably not worth worrying about.
