### PR TITLE
[bugfix] set num_threads to min(n,p) -- closes #229

### LINKED ISSUE #229: OMP scans incorrect when N < P
OMP scans are incorrect when the length of the input is smaller than the number of threads.

See scanopenmp.hxx:134-135.
134  `exclusive_inplace(seq_exec{}, begin + i0, begin + i1, f, init);`
135  `sums[pid] = *(begin + i1 - 1);`

### PR DESCRIPTION
**Pull request by willkill07**

### CODE REVIEW

File: include/RAJA/internal/exec-openmp/scan_openmp.hxx [hunk 1]
```diff
@@ -90,17 +90,17 @@ void inclusive_inplace(const ::RAJA::omp_parallel_for_exec&,
 {
   using Value = typename ::std::iterator_traits<Iter>::value_type;
   const int n = end - begin;
-  const int p = omp_get_max_threads();
+  const int p = std::min(n, omp_get_max_threads());
   ::std::vector<Value> sums(p, Value());
-#pragma omp parallel
+  #pragma omp parallel num_threads(p)
```
Comment (davidbeckingsale) [inline include/RAJA/internal/exec-openmp/scan_openmp.hxx]: Can you get rid of the indent on the pragmas, so that we are consistent with the rest of the code.

Comment (willkill07) [inline include/RAJA/internal/exec-openmp/scan_openmp.hxx]: Done.

**Comment by davidbeckingsale** [comment]
@willkill07 I'm guessing the exclusive is failing, the tests passed before that commit.

**Comment by willkill07** [comment]
The tests pass on my own machines -- specifically, it fails on GCC-6 on travis but passes on GCC-6 on my arch system along with my MacBook Pro. Looking into the output given on Travis CI to see what's going on...

**Comment by davidbeckingsale** [comment]
Looks like this is going to pass. If you remove the extra travis stuff we can merge this. Thanks!

**Comment by willkill07** [comment]
Should be good to go
