### PR TITLE
Fix header order issue with hip and vectorization

### LINKED ISSUE #1809: Header include order bug with hip+vectorization when compiling with hip inactive
**Describe the bug**

When hip and vectorization are enabled in the same build and hip is not active there is a header ordering bug. The policy tensor arch hip traits header relies on values in the policy hip policy header. In RAJA.hpp the pattern pattern header is included first, then the policy tensor header, then policy hip policy header.
AS an aside, the pattern tensor header includes things in the policy tensor directory header which seems to circumvent the separation of pattern and policy.
This works normally because the pattern forall header includes the util resource header which, when hip is active, includes the policy hip policy header. The pattern forall header is included before the pattern tensor header so so the values are available.

**To Reproduce**

Build RAJA with hip and try to compile a c++ file as c++ instead of as hip.

**Expected behavior**

It should compile without error.
It should also be caught by our testing.

**Compilers & Libraries (please complete the following information):**
 - Compiler & version: rocm + cce + gcc13

**Additional context**

```
In file included from .../include/RAJA/RAJA.hpp:54:
In file included from .../include/RAJA/pattern/tensor.hpp:22:
In file included from .../include/RAJA/pattern/tensor/internal/RegisterBase.hpp:30:
In file included from .../include/RAJA/policy/tensor/arch.hpp:150:
.../include/RAJA/policy/tensor/arch/hip/traits.hpp:37:15: error: no member named 'hip' in namespace 'RAJA::policy'
   37 |       policy::hip::device_constants.WARP_SIZE;
      |       ~~~~~~~~^
```

### PR DESCRIPTION
**Pull request by MrBurmark**
# Summary

Explicitly use RAJA_HIP_WAVESIZE in the tensor arch hip files to avoid a header order issue.

- This PR is a bugfix
- It does the following (modify list as needed):
  - Fixes #1809 

# Design review (for API changes or additions---delete if unneeded)

On (date), we reviewed this PR.  We discussed the design ideas:

1. First idea or goal
2. Second idea
3. Third idea

This PR implements 1. and 3.  It leaves out 2. for the following reasons

- (impractical)
- (too big)
- (not a good idea anyway)

### CODE REVIEW

**Review by rhornung67 — APPROVED** [review]

**Comment by MrBurmark** [comment]
Manually testing my hacky way of building as CXX seems to build them as CXX and link them as HIP but then the executable can't find the hip runtime. So I'll probably take those tests out and make an issue for us to try to test them some other way.

File: include/RAJA/policy/cuda/intrinsics.hpp [hunk 1]
```diff
@@ -23,7 +23,7 @@
 
 #include "RAJA/config.hpp"
 
-#if defined(RAJA_ENABLE_CUDA)
+#if defined(RAJA_CUDA_ACTIVE)
```
Comment (adayton1) [inline include/RAJA/policy/cuda/intrinsics.hpp:26]: What's the difference between these macros?

Comment (rhornung67) [reply include/RAJA/policy/cuda/intrinsics.hpp:26]: I believe `RAJA_ENABLE_CUDA` is true when CUDA is enabled in the build and that `RAJA_CUDA_ACTIVE` is true when a code region is being compiled for the device. Somebody, please check me on this.

**Review by adayton1 — APPROVED** [review]

File: include/RAJA/policy/cuda/intrinsics.hpp (hunk 1 above)
Comment (MrBurmark) [reply include/RAJA/policy/cuda/intrinsics.hpp:26]: Yep, its about allowing you to use the same RAJA that was configured with gpus in both files compiled as cuda/hip and files compiled as cpp (without a gpu compiler).
