### PR TITLE
Fix unnecessary init for inclusive scans

### LINKED ISSUE #194: Inclusive scan init value argument confusing
Inclusive scans take a value argument that is not used. This is confusing and not found in other scan APIs.

### PR DESCRIPTION
**Pull request by willkill07**
This closes #194

### CODE REVIEW

**Comment by willkill07** [comment]
Looks like the CI passed after resolving some extra template issues.

File: include/RAJA/exec-cuda/scan_cuda.hxx [hunk 1]
```diff
@@ -80,8 +80,7 @@ template <typename InputIter, typename Function, typename T>
 void inclusive_inplace(const ::RAJA::cuda_exec_base&,
```
Comment (davidbeckingsale) [inline include/RAJA/exec-cuda/scan_cuda.hxx]: There are leftover template parameters here that actually break the cuda-enabled build. I'm fixing them in #139

Comment (davidbeckingsale) [inline include/RAJA/exec-cuda/scan_cuda.hxx]: Pinging @willkill07
